development:
  adapter: mysql
  encoding: utf8
  database: jeeter_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: jeeter_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: jeeter_production
  pool: 5
  username: root
  password:
