development:
  adapter: mysql
  encoding: utf8
  database: railspress_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: railspress_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: railspress_production
  pool: 5
  username: root
  password:
